#!/command/with-contenv bash

set -e

echo "Starting moltis..."

SHARE_PATH="$HOME/.local/moltis/share/moltis"
moltis gateway \
        --bind "${MOLTIS_GATEWAY_BIND:-0.0.0.0}" \
        --port "${MOLTIS_GATEWAY_PORT:-18789}" \
        --share-dir "${SHARE_PATH}" \
        --no-tls